// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0CrKwis33cOsUeIxlyNgiDL-MH7at_M',
    appId: '1:629010929009:web:ddc10053e1224d550152d0',
    messagingSenderId: '629010929009',
    projectId: 'cost-a4080',
    authDomain: 'cost-a4080.firebaseapp.com',
    storageBucket: 'cost-a4080.appspot.com',
    measurementId: 'G-F3FFV4L7TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcr5mr5-p9DrZ8rgvsimS6kPGhIew1ygk',
    appId: '1:629010929009:android:10147b6b4cb28a290152d0',
    messagingSenderId: '629010929009',
    projectId: 'cost-a4080',
    storageBucket: 'cost-a4080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJW1SjGH63n_E-2UevaVd11F3_tnP2ENs',
    appId: '1:629010929009:ios:36c63b599b6e5d370152d0',
    messagingSenderId: '629010929009',
    projectId: 'cost-a4080',
    storageBucket: 'cost-a4080.appspot.com',
    androidClientId: '629010929009-oo3jmeuask3841tj1ts1k83mtv3vcv2m.apps.googleusercontent.com',
    iosClientId: '629010929009-26g02covqa5ai4n8nboikk7ffmgfpacb.apps.googleusercontent.com',
    iosBundleId: 'com.example.costAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJW1SjGH63n_E-2UevaVd11F3_tnP2ENs',
    appId: '1:629010929009:ios:36c63b599b6e5d370152d0',
    messagingSenderId: '629010929009',
    projectId: 'cost-a4080',
    storageBucket: 'cost-a4080.appspot.com',
    androidClientId: '629010929009-oo3jmeuask3841tj1ts1k83mtv3vcv2m.apps.googleusercontent.com',
    iosClientId: '629010929009-26g02covqa5ai4n8nboikk7ffmgfpacb.apps.googleusercontent.com',
    iosBundleId: 'com.example.costAdmin',
  );
}
